export type Language = "vi" | "en";

export const ui = {
  vi: {
    skip: "Đi đến nội dung chính",
    language: "EN",
    reserve: "Đặt lịch trải nghiệm",
    nav: { journey: "Hành trình", forYou: "Dành cho bạn", signatures: "Signature", collection: "Dịch vụ", visit: "Ghé thăm" },
    common: {
      minutes: "phút",
      listed: "Giá niêm yết",
      direct: "Giá ưu đãi khi đặt trực tiếp",
      privilege: "Ưu đãi đặt trực tiếp · 20%",
      detail: "Khám phá dịch vụ",
      choose: "Chọn trải nghiệm này",
      legal: "Dịch vụ hướng đến chăm sóc thẩm mỹ và thư giãn, không thay thế việc khám, chẩn đoán hoặc điều trị y khoa.",
    },
    journey: {
      progress: ["Arrival", "Threshold", "Pause", "Skin", "Body", "Retreat"],
      scenes: {
        arrival: {
          eyebrow: "PRIVATE BOTANICAL SKIN & BODY RETREAT · SÀI GÒN",
          title: ["Rời nhịp phố.", "Bước vào", "một khoảng riêng."],
          body: "Tại villa phủ xanh giữa Trung Sơn, những trải nghiệm chăm sóc da và cơ thể được chuẩn bị theo nhịp riêng — yên tĩnh, kín đáo và chỉn chu.",
          primary: "Bước vào SĀKURĀ",
          secondary: "Đặt lịch trực tiếp",
          meta: "MỞ CỬA HẰNG NGÀY · 09:00 — 20:30",
        },
        threshold: {
          eyebrow: "02 · CROSSING THE THRESHOLD",
          title: "Một khoảng xanh mở ra, vừa đủ xa nhịp sống bên ngoài.",
          body: "Ánh sáng tự nhiên, chất liệu mộc và sự riêng tư đưa bạn chậm lại ngay từ khoảnh khắc bước qua cánh cửa.",
          meta: "QUIET LUXURY IN NATURE",
        },
        pause: {
          eyebrow: "03 · YOUR TIME AT SĀKURĀ",
          title: "Hôm nay, bạn muốn dành thời gian cho điều gì?",
          body: "Mỗi nhu cầu mở ra một không gian chăm sóc riêng, với thời lượng và nhịp trải nghiệm phù hợp.",
          items: [
            ["01", "Làn da", "Làm sạch, bổ sung độ ẩm và chăm sóc bề mặt da trong không gian riêng tư."],
            ["02", "Cơ thể", "Hơi ấm, chất liệu tự nhiên và các thao tác được điều chỉnh theo cảm nhận của bạn."],
            ["03", "Chính mình", "Một khoảng tĩnh lặng để tạm rời lịch trình và tận hưởng thời gian trọn vẹn."],
          ],
        },
        facial: {
          eyebrow: "04 · FACIAL RETREAT",
          title: "Làn da được nâng niu trong từng lớp chăm sóc.",
          body: "Từ làm sạch dịu nhẹ, bổ sung độ ẩm đến các lựa chọn Signature, mỗi trải nghiệm Facial được chuẩn bị theo tình trạng và cảm nhận của làn da khi bạn ghé thăm.",
          meta: "REAL SKIN · CONSIDERED CARE",
        },
        body: {
          eyebrow: "05 · BODY RETREAT",
          title: "Một khoảng lặng ấm áp dành cho cơ thể.",
          body: "Đá ấm, ngải cứu, gừng, đá muối và nến dưỡng được sử dụng bên ngoài da, trong không gian kín đáo và với mức độ thao tác được trao đổi trước cùng bạn.",
          meta: "WARM · PRIVATE · UNHURRIED",
        },
        retreat: {
          eyebrow: "06 · THE PRIVATE RETREAT",
          title: "Tĩnh lặng. Riêng tư. Được chuẩn bị cho bạn.",
          body: "Từ lựa chọn dịch vụ đến khoảnh khắc bạn rời SĀKURĀ, mỗi điểm chạm đều được chăm chút để trải nghiệm diễn ra liền mạch và thư thái.",
          primary: "Khám phá các dịch vụ",
          secondary: "Dành lịch hẹn",
        },
      },
    },
    welcome: {
      eyebrow: "THE SĀKURĀ WELCOME",
      title: "Từng chi tiết, dành trọn cho thời gian của bạn.",
      body: "Từ khoảnh khắc chào đón đến khi trải nghiệm khép lại, không gian, nhịp phục vụ và sự chuẩn bị đều hướng đến một cảm giác: bạn được chăm sóc theo cách riêng của mình.",
      pillars: [
        ["Không gian riêng tư", "Villa nhiều mảng xanh, ánh sáng tự nhiên và chất liệu mộc mang đến cảm giác tách biệt nhưng vẫn gần trung tâm thành phố."],
        ["Nhịp phục vụ thư thái", "Mỗi lịch hẹn được sắp xếp với khoảng thời gian phù hợp, để trải nghiệm diễn ra thong thả, liền mạch và trọn vẹn."],
        ["Chăm sóc cá nhân hóa", "Trước khi bắt đầu, chuyên viên trao đổi về tình trạng da hoặc cơ thể, sở thích và những lưu ý cần thiết để chuẩn bị phù hợp."],
      ],
    },
    finder: {
      eyebrow: "CURATED FOR YOU",
      title: "Bạn muốn dành khoảng thời gian này cho điều gì?",
      body: "Chọn nhu cầu và thời lượng mong muốn. SĀKURĀ sẽ gợi ý những trải nghiệm phù hợp, kèm thời gian và mức giá để bạn dễ dàng lựa chọn.",
      focusLabel: "Nhu cầu của bạn",
      focus: { facial: ["Làn da", "Facial Retreat"], body: ["Cơ thể", "Body Retreat"] },
      timeLabel: "Thời lượng mong muốn",
      time: { any: "SĀKURĀ gợi ý", short: "Khoảng 60 phút", classic: "Khoảng 90 phút", extended: "100 phút trở lên" },
      result: "Gợi ý phù hợp dành cho bạn",
      viewTimes: "Xem lịch trống",
    },
    signatures: {
      eyebrow: "SIGNATURE FACIAL EXPERIENCES",
      title: "Những trải nghiệm làm nên dấu ấn SĀKURĀ.",
      body: "Ba lựa chọn Facial Signature được giới thiệu như những chương riêng — nơi sản phẩm, chất liệu và nhịp chăm sóc cùng tạo nên một trải nghiệm đáng nhớ.",
      emotional: [
        "Hơi ấm của đá hòa cùng từng bước chăm sóc, mang lại cảm giác êm dịu và thư thái cho làn da.",
        "Sắc vàng 24K gặp ánh sáng tự nhiên, tạo nên một khoảng chăm sóc tinh tế và rạng rỡ.",
        "Một trải nghiệm đa bước dành cho khách mong muốn làn da được chăm chút kỹ lưỡng và trọn vẹn hơn.",
      ],
    },
    bodyFeature: {
      eyebrow: "BODY RETREAT",
      title: "Hơi ấm dẫn lối vào một nhịp thư thái hơn.",
      body: "Không gian chuyển sang sắc ấm, chuyển động chậm lại. Đá ấm được sử dụng bên ngoài da trong trải nghiệm chăm sóc cơ thể kín đáo, với mức độ thao tác được trao đổi cùng bạn trước khi bắt đầu.",
      note: "90 PHÚT · WARM STONE BODY CARE",
    },
    collection: {
      eyebrow: "THE RETREAT COLLECTION",
      title: "Chọn trải nghiệm phù hợp với khoảng thời gian của bạn.",
      body: "Khám phá trọn bộ Facial Retreat, Signature Facial và Body Retreat. Mỗi lựa chọn đều hiển thị rõ thời lượng, giá niêm yết và giá ưu đãi khi đặt trực tiếp tại website.",
      filters: { all: "Tất cả", facial: "Facial", signature: "Signature", body: "Body" },
      privilegeTitle: "Đặc quyền 20% khi đặt lịch trực tiếp",
      privilegeBody: "Khi đặt lịch tại sakuraretreat.vn, mọi dịch vụ được áp dụng mức ưu đãi còn 80% giá niêm yết. Mức giá ưu đãi luôn được hiển thị trước khi bạn gửi yêu cầu.",
      suitable: "Phù hợp khi bạn mong muốn",
      facialSuitable: "Một trải nghiệm chăm sóc bề mặt da nhẹ nhàng, có trao đổi trước về tình trạng da, mức độ nhạy cảm và nhu cầu hiện tại.",
      bodySuitable: "Một khoảng chăm sóc cơ thể ấm áp, kín đáo và được điều chỉnh theo mức độ thoải mái của bạn.",
      preparation: "SĀKURĀ sẽ chuẩn bị",
      facialPreparation: "Không gian riêng, sản phẩm chăm sóc phù hợp và thời lượng dành trọn cho dịch vụ bạn đã chọn.",
      bodyPreparation: "Không gian riêng, chất liệu sử dụng bên ngoài da và nhịp chăm sóc phù hợp với lưu ý của bạn.",
      close: "Đóng",
    },
    bookingLead: {
      eyebrow: "YOUR PRIVATE TIME",
      title: "Khoảng thời gian của bạn, được chuẩn bị chu đáo.",
      body: "Chọn trải nghiệm và giờ ghé thăm thuận tiện. Đội ngũ đặt lịch sẽ kiểm tra lịch trống, liên hệ xác nhận và chuẩn bị phòng riêng trước khi đón bạn.",
      cta: "Bắt đầu đặt lịch",
      notes: ["6 bước ngắn gọn", "Không tải lại trang", "Xác nhận trước khi đến"],
    },
    booking: {
      eyebrow: "PRIVATE RESERVATION",
      step: "Bước",
      of: "trên",
      intentEyebrow: "01 · KHOẢNG THỜI GIAN CỦA BẠN",
      intentTitle: "Bạn muốn dành thời gian cho điều gì?",
      intents: { facial: ["Skin", "Chăm sóc làn da"], body: ["Body", "Chăm sóc cơ thể"], signature: ["Signature", "Dấu ấn SĀKURĀ"] },
      serviceEyebrow: "02 · CHỌN DỊCH VỤ",
      serviceTitle: "Trải nghiệm nào phù hợp với bạn hôm nay?",
      dateEyebrow: "03 · NGÀY GHÉ THĂM",
      dateTitle: "Khi nào thuận tiện để đón bạn?",
      timeEyebrow: "04 · GIỜ BẮT ĐẦU",
      timeTitle: "Chọn khung giờ bạn mong muốn.",
      guestEyebrow: "05 · THÔNG TIN ĐÓN TIẾP",
      guestTitle: "SĀKURĀ có thể liên hệ với bạn bằng cách nào?",
      name: "Họ và tên",
      namePlaceholder: "Tên của bạn",
      phone: "Số điện thoại",
      note: "Điều SĀKURĀ nên lưu ý — không bắt buộc",
      notePlaceholder: "Tình trạng da, mức độ nhạy cảm hoặc lưu ý dành cho chuyên viên...",
      privacy: "Thông tin chỉ được sử dụng để hỗ trợ yêu cầu đặt lịch này.",
      next: "Tiếp tục",
      back: "Quay lại",
      complete: "Hoàn tất yêu cầu",
      readyEyebrow: "06 · YÊU CẦU ĐÃ ĐƯỢC GỬI",
      readyTitle: "SĀKURĀ đã nhận yêu cầu đặt lịch của bạn.",
      readyBody: "Yêu cầu đã được gửi đến đội ngũ SĀKURĀ. Chúng tôi sẽ kiểm tra lịch trống và liên hệ xác nhận lại dịch vụ, thời gian cùng mức giá trước khi đón bạn.",
      zalo: "Liên hệ thêm qua Zalo",
      whatsapp: "Liên hệ thêm qua WhatsApp",
      messenger: "Mở Messenger",
      call: "Gọi 09123 555 03",
      again: "Chọn lại",
      confirmation: "Lịch hẹn hoàn tất sau khi đội ngũ SĀKURĀ liên hệ xác nhận.",
    },
    visit: {
      eyebrow: "ARRIVE AT SĀKURĀ",
      title: "SĀKURĀ đang chờ đón bạn tại Trung Sơn.",
      address: "05 Đường số 4A, Khu dân cư Trung Sơn – Him Lam, Bình Hưng, TP.HCM",
      hint: "Khu dân cư Trung Sơn – Him Lam",
      directions: "Mở chỉ đường Google Maps",
    },
    concierge: {
      eyebrow: "RESERVATION & GUEST ASSISTANCE",
      title: "Đội ngũ SĀKURĀ sẵn sàng hỗ trợ lịch hẹn của bạn.",
      body: "Liên hệ SĀKURĀ để được tư vấn lựa chọn phù hợp, kiểm tra khung giờ, xác nhận lịch hẹn hoặc hướng dẫn đường đến retreat.",
      vietnam: "Liên hệ tại Việt Nam",
      international: "International Guest Assistance",
      zalo: "Zalo",
      messenger: "Messenger",
      whatsapp: "WhatsApp",
      call: "Gọi trực tiếp",
      showQr: "Hiển thị mã QR",
      closeQr: "Đóng mã QR",
      scan: "Quét mã bằng ứng dụng tương ứng để liên hệ đội ngũ SĀKURĀ.",
    },
    footer: { line: "Private Botanical Skin & Body Retreat", idea: "Quiet Luxury in Nature", hours: "Hằng ngày · 09:00 — 20:30", top: "Về đầu trang" },
  },
  en: {
    skip: "Skip to the main experience",
    language: "VI",
    reserve: "Reserve an experience",
    nav: { journey: "Journey", forYou: "For you", signatures: "Signatures", collection: "Experiences", visit: "Visit" },
    common: {
      minutes: "minutes",
      listed: "Listed price",
      direct: "Direct website rate",
      privilege: "Direct reservation privilege · 20%",
      detail: "Explore this experience",
      choose: "Choose this experience",
      legal: "Experiences are intended for aesthetic care and relaxation and do not replace medical examination, diagnosis or treatment.",
    },
    journey: {
      progress: ["Arrival", "Threshold", "Pause", "Skin", "Body", "Retreat"],
      scenes: {
        arrival: {
          eyebrow: "PRIVATE BOTANICAL SKIN & BODY RETREAT · SAIGON",
          title: ["Leave the city.", "Enter", "a private retreat."],
          body: "Inside a botanical villa in Trung Son, facial and body experiences are prepared with an unhurried pace, privacy and considered attention.",
          primary: "Enter SĀKURĀ",
          secondary: "Reserve directly",
          meta: "OPEN DAILY · 09:00 — 20:30",
        },
        threshold: {
          eyebrow: "02 · CROSSING THE THRESHOLD",
          title: "A botanical setting, just far enough from the pace outside.",
          body: "Natural light, honest materials and a sense of privacy invite you to slow down from the moment you cross the threshold.",
          meta: "QUIET LUXURY IN NATURE",
        },
        pause: {
          eyebrow: "03 · YOUR TIME AT SĀKURĀ",
          title: "What would you like this time to be for?",
          body: "Each need opens into its own private setting, with a duration and pace considered around you.",
          items: [
            ["01", "Your skin", "Cleansing, hydration and considered surface care in a private setting."],
            ["02", "Your body", "Warmth, natural materials and a level of touch discussed with you."],
            ["03", "Yourself", "A quiet interval away from the schedule, with time to simply be present."],
          ],
        },
        facial: {
          eyebrow: "04 · FACIAL RETREAT",
          title: "Considered care, layer by layer.",
          body: "From gentle cleansing and hydration to our Signature selections, every Facial experience is prepared around how your skin feels when you arrive.",
          meta: "REAL SKIN · CONSIDERED CARE",
        },
        body: {
          eyebrow: "05 · BODY RETREAT",
          title: "A warm, quiet interval for the body.",
          body: "Warm stones, mugwort, ginger, salt stones and cosmetic candle care are used externally in a discreet setting, with the level of touch discussed before we begin.",
          meta: "WARM · PRIVATE · UNHURRIED",
        },
        retreat: {
          eyebrow: "06 · THE PRIVATE RETREAT",
          title: "Quiet. Private. Prepared for you.",
          body: "From choosing an experience to the moment you leave, every touchpoint is considered so your time at SĀKURĀ feels seamless and unhurried.",
          primary: "Explore the collection",
          secondary: "Reserve your time",
        },
      },
    },
    welcome: {
      eyebrow: "THE SĀKURĀ WELCOME",
      title: "Every detail, devoted to your time.",
      body: "From the first welcome to the close of your experience, the setting, pace and preparation share one intention: care that feels distinctly your own.",
      pillars: [
        ["A private setting", "A botanical villa, natural daylight and honest materials create a sense of distance while remaining close to the city."],
        ["An unhurried pace", "Each appointment is arranged with the time it needs, allowing your experience to unfold seamlessly and without haste."],
        ["Care considered around you", "Before beginning, your specialist asks about your skin or body, preferences and anything that should be noted."],
      ],
    },
    finder: {
      eyebrow: "CURATED FOR YOU",
      title: "What would you like this time to be for?",
      body: "Choose your focus and preferred duration. SĀKURĀ will suggest the closest experiences, with time and pricing presented clearly for your decision.",
      focusLabel: "Your focus",
      focus: { facial: ["Your skin", "Facial Retreat"], body: ["Your body", "Body Retreat"] },
      timeLabel: "Preferred duration",
      time: { any: "Let SĀKURĀ suggest", short: "Around 60 minutes", classic: "Around 90 minutes", extended: "100 minutes or more" },
      result: "A considered selection for you",
      viewTimes: "View available times",
    },
    signatures: {
      eyebrow: "SIGNATURE FACIAL EXPERIENCES",
      title: "The experiences that define SĀKURĀ.",
      body: "Three Signature Facial selections unfold as individual chapters, where product, material and pace create a memorable sense of care.",
      emotional: [
        "The warmth of stone accompanies each step, creating a gentle and deeply comfortable facial experience.",
        "24K cosmetic care meets natural light in a refined experience centred on softness and radiance.",
        "A multi-step experience for guests who would like their skin to receive more complete, considered attention.",
      ],
    },
    bodyFeature: {
      eyebrow: "BODY RETREAT",
      title: "Warmth leads into a slower pace.",
      body: "The light becomes warmer and movement slows. Warm stones are used externally in a discreet body-care experience, with the level of touch discussed before beginning.",
      note: "90 MINUTES · WARM STONE BODY CARE",
    },
    collection: {
      eyebrow: "THE RETREAT COLLECTION",
      title: "Choose an experience that suits your time.",
      body: "Explore the complete Facial Retreat, Signature Facial and Body Retreat collection. Every selection clearly presents its duration, listed price and direct website rate.",
      filters: { all: "All", facial: "Facial", signature: "Signature", body: "Body" },
      privilegeTitle: "20% privilege for direct reservations",
      privilegeBody: "When you reserve through sakuraretreat.vn, every experience is offered at 80% of its listed price. Your direct rate is always shown before you send a request.",
      suitable: "Consider this when you would like",
      facialSuitable: "A gentle surface-care experience with a prior conversation about your skin, sensitivity and current needs.",
      bodySuitable: "A warm, discreet body-care pause adjusted to your preferred level of comfort.",
      preparation: "SĀKURĀ will prepare",
      facialPreparation: "A private setting, appropriate skincare and the full time allocated to your chosen experience.",
      bodyPreparation: "A private setting, externally used materials and a pace considered around anything you would like us to note.",
      close: "Close",
    },
    bookingLead: {
      eyebrow: "YOUR PRIVATE TIME",
      title: "Your time, thoughtfully prepared.",
      body: "Choose your experience and preferred arrival time. Our reservation team will review availability, confirm the details and prepare your private room before you arrive.",
      cta: "Begin your reservation",
      notes: ["Six concise steps", "No page reload", "Personally confirmed"],
    },
    booking: {
      eyebrow: "PRIVATE RESERVATION",
      step: "Step",
      of: "of",
      intentEyebrow: "01 · YOUR TIME",
      intentTitle: "What would you like this time to be for?",
      intents: { facial: ["Skin", "Facial care"], body: ["Body", "Body care"], signature: ["Signature", "The SĀKURĀ edit"] },
      serviceEyebrow: "02 · CHOOSE AN EXPERIENCE",
      serviceTitle: "Which experience feels right today?",
      dateEyebrow: "03 · YOUR VISIT",
      dateTitle: "When may we welcome you?",
      timeEyebrow: "04 · ARRIVAL TIME",
      timeTitle: "Choose your preferred start time.",
      guestEyebrow: "05 · WELCOME DETAILS",
      guestTitle: "How may SĀKURĀ reach you?",
      name: "Full name",
      namePlaceholder: "Your name",
      phone: "Phone number",
      note: "Anything SĀKURĀ should note — optional",
      notePlaceholder: "Skin sensitivity or anything you would like your specialist to note...",
      privacy: "Your details are used only to support this appointment request.",
      next: "Continue",
      back: "Back",
      complete: "Complete request",
      readyEyebrow: "06 · REQUEST SENT",
      readyTitle: "SĀKURĀ has received your reservation request.",
      readyBody: "Your request has been sent to the SĀKURĀ team. We will review availability and contact you to confirm the experience, arrival time and rate before your visit.",
      zalo: "Contact us via Zalo",
      whatsapp: "Contact us via WhatsApp",
      messenger: "Open Messenger",
      call: "Call +84 9123 555 03",
      again: "Choose again",
      confirmation: "Your appointment is complete once the SĀKURĀ team confirms it with you.",
    },
    visit: {
      eyebrow: "ARRIVE AT SĀKURĀ",
      title: "SĀKURĀ awaits you in Trung Son.",
      address: "05 Street 4A, Trung Son – Him Lam Residential Area, Binh Hung, Ho Chi Minh City",
      hint: "Trung Son – Him Lam Residential Area",
      directions: "Open directions in Google Maps",
    },
    concierge: {
      eyebrow: "RESERVATION & GUEST ASSISTANCE",
      title: "The SĀKURĀ team is ready to assist with your visit.",
      body: "Contact us for guidance on selecting an experience, checking available times, confirming your appointment or finding your way to the retreat.",
      vietnam: "Vietnam Guest Assistance",
      international: "International Guest Assistance",
      zalo: "Zalo",
      messenger: "Messenger",
      whatsapp: "WhatsApp",
      call: "Direct call",
      showQr: "Show QR code",
      closeQr: "Close QR code",
      scan: "Scan with the relevant mobile app to contact the SĀKURĀ team.",
    },
    footer: { line: "Private Botanical Skin & Body Retreat", idea: "Quiet Luxury in Nature", hours: "Daily · 09:00 — 20:30", top: "Back to top" },
  },
} as const;

export const descriptionsEn: Record<string, string> = {
  AC016: "A gentle surface cleanse that removes daily impurities and excess oil, leaving skin feeling fresh, clear and comfortable.",
  AC017: "A multi-step surface-cleansing experience for skin prone to excess oil and congestion, supporting a clean and balanced feel.",
  FF021: "Gentle cleansing and hydration leave the skin surface feeling soft, fresh and visibly smooth after the experience.",
  FF023: "Cleansing and hydration with externally applied cosmetics help the skin surface appear fresh, soft and more even in tone.",
  FF024: "Hydrating care with suitable skincare products leaves the skin surface feeling softer, smoother and more comfortable.",
  FF029: "A multi-step surface cleanse removes daily impurities, excess oil and cosmetic residue for a fresh and comfortable skin feel.",
  SK029: "Facial care combined with warm stones used gently and externally creates soothing warmth while leaving the skin surface feeling soft.",
  FA034: "Facial care with externally applied 24K cosmetic products combines cleansing and hydration for a soft, smooth and visibly radiant skin surface.",
  "YOUTHFUL-GLOW": "A considered multi-step experience centred on cleansing, hydration and surface softness, helping skin appear fresh and carefully cared for.",
  FA036: "Externally applied skincare products help cleanse and soften the outermost skin surface for a fresh, smooth and renewed feeling.",
  FA037: "Gentle cleansing and hydration leave the skin surface feeling soothed, soft and balanced.",
  "DIAMOND-FACE": "Multi-step facial care with externally applied cosmetics focuses on cleansing and hydration for a soft, smooth and fresh-looking skin surface.",
  "DIAMOND-NECK": "External cleansing, hydration and skincare for the neck area help the skin surface feel soft, smooth and evenly cared for.",
  BD002: "Relaxing body care with warm stones used externally creates a warm, comfortable feeling and an unhurried pause after a long day.",
  BD003: "Relaxing body care with warm stones used externally creates a warm, comfortable feeling and an unhurried pause after a long day.",
  BD005: "Gentle body care with warm mugwort used externally creates a soothing, warm and comfortable experience.",
  BD007: "Externally applied ginger products and warm Himalayan salt stones create a gentle, warm and unhurried body-care experience.",
  BD008: "Suitable cosmetic candle care creates gentle warmth when applied externally, helping the skin surface feel soft while you relax.",
  BD011: "Gentle external care focuses on the neck and shoulders for guests seeking a quiet pause after long periods of sitting or working.",
  BD012: "Relaxing neck-and-shoulder care with an external warm wrap creates a soothing, comfortable and unhurried experience.",
  BR050: "Externally applied body-care cosmetics combine cleansing and hydration to leave the skin surface looking fresh, soft and smooth.",
};
